### ISSUE TITLE
Improve set library

### ISSUE THREAD

**Issue by pkieltyka** [Workiva/go-datastructures#104]
Hello,

Perhaps replace the set library here with https://github.com/xtgo/set and offer credit?

**Comment by pkieltyka** [comment]
btw, I wrapped it with a few methods here: https://github.com/goware/set .. perhaps you guys can do something like this, and even better?

**Comment by alexandercampbell-wf** [comment]
@pkieltyka thanks for the information. xtgo/set and our Set implementation appear to have completely different approaches. We implement a Set struct with only basic methods: `Add`, `Has`, `Len`, and so on. The xtgo/set approach works on `sort.Interface`, but includes much richer functionality.

Since our approaches are so different and have different use cases, I'd prefer to keep them separate. However, I've opened a PR here to update the documentation and point to the repositories you mentioned: https://github.com/Workiva/go-datastructures/pull/135.

Thanks!
