### ISSUE TITLE
Merge with emirpasic/gods ?

### ISSUE THREAD

**Issue by andygrunwald** [Workiva/go-datastructures#98]
A few days ago i found https://github.com/emirpasic/gods.

```
Go Data Structures. Tags: Containers, Sets, Lists, Stacks, Maps, Trees, HashSet, TreeSet, ArrayList, SinglyLinkedList, DoublyLinkedList, LinkedListStack, ArrayStack, HashMap, TreeMap, RedBlackTree, BinaryHeap, Comparator, Sort
```

Maybe it make sense to merge both together? Or to benefit from each other?

**Comment by andygrunwald** [comment]
No response since ~6 month. So i think this is not wanted

**Comment by alexandercampbell-wf** [comment]
@andygrunwald sorry about the delay. `gods` does look promising, but merging the projects would be a lot of work due to conflicting designs. I'll bring this up for discussion with my team. I do like the interfaces defined in `gods` and it may be worth satisfying those interfaces with go-datastructures implementations.

For what it's worth, `Workiva/go-datastructures` is currently ~5 times larger than `emirpasic/gods`:

```sh
wc -l $(git ls-files | grep "go$")
```

`gods` has 5,908 lines, while `go-datastructures` has 26,046.

**Comment by andygrunwald** [comment]
With merging i mean "merge both projects together". In what direction, doesn`t matter.
But maybe a link to gods might be cool to know what projects in this area exists as well.
